services:
    _defaults:
        autowire: true
        autoconfigure: true
    
    InspiredMinds\ContaoDynamicPtableBackport\:
        resource: ../src
        exclude: ../src/{ContaoManager,DependencyInjection}
